### ISSUE TITLE
AssertionError at /user/update Class InputSerializer missing "Meta" attribute

### ISSUE THREAD

**Issue by Kattenelvis** [Gofven/flowback-backend#130]
can rely on getting a response instead of an exception.
    """
    if iscoroutinefunction(get_response):
        @wraps(get_response)
        async def inner(request):
            try:
                response = await get_response(request)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
            except Exception as exc:
                response = await sync_to_async(
                    response_for_exception, thread_sensitive=False
                )(request, exc)
            return response
Local vars
D:\Files\flowback-backend\venv\Lib\site-packages\django\core\handlers\base.py, line 253, in _get_response_async
            wrapped_callback = self.make_view_atomic(callback)
            # If it is a synchronous view, run it in a subthread
            if not iscoroutinefunction(wrapped_callback):
                wrapped_callback = sync_to_async(
                    wrapped_callback, thread_sensitive=True
                )
            try:
                response = await wrapped_callback(
                                 …
                    request, *callback_args, **callback_kwargs
                )
            except Exception as e:
                response = await sync_to_async(
                    self.process_exception_by_middleware,
                    thread_sensitive=True,
Local vars
C:\Users\Katte\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py, line 58, in run
        self.kwargs = kwargs
    def run(self):
        if not self.future.set_running_or_notify_cancel():
            return
        try:
            result = self.fn(*self.args, **self.kwargs)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
        except BaseException as exc:
            self.future.set_exception(exc)
            # Break a reference cycle with the exception 'exc'
            self = None
        else:
            self.future.set_result(result)
Local vars
D:\Files\flowback-backend\venv\Lib\site-packages\django\views\decorators\csrf.py, line 56, in wrapper_view
def csrf_exempt(view_func):
    """Mark a view function as being exempt from the CSRF view protection."""
    # view_func.csrf_exempt = True would also work, but decorators are nicer
    # if they don't have side effects, so return a new function.
    @wraps(view_func)
    def wrapper_view(*args, **kwargs):
        return view_func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^ …
    wrapper_view.csrf_exempt = True
    return wrapper_view
Local vars
D:\Files\flowback-backend\venv\Lib\site-packages\django\views\generic\base.py, line 104, in view
            self = cls(**initkwargs)
            self.setup(request, *args, **kwargs)
            if not hasattr(self, "request"):
                raise AttributeError(
                    "%s instance has no 'request' attribute. Did you override "
                    "setup() and forget to call super()?" % cls.__name__
                )
            return self.dispatch(request, *args, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
        view.view_class = cls
        view.view_initkwargs = initkwargs
        # __name__ and __qualname__ are intentionally left unchanged as
        # view_class should be used to robustly determine the name of the view
Local vars
D:\Files\flowback-backend\venv\Lib\site-packages\rest_framework\views.py, line 509, in dispatch
                                  self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed
            response = handler(request, *args, **kwargs)
        except Exception as exc:
            response = self.handle_exception(exc)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^ …
        self.response = self.finalize_response(request, response, *args, **kwargs)
        return self.response
    def options(self, request, *args, **kwargs):
        """
Local vars
D:\Files\flowback-backend\venv\Lib\site-packages\rest_framework\views.py, line 469, in handle_exception
        exception_handler = self.get_exception_handler()
        context = self.get_exception_handler_context()
        response = exception_handler(exc, context)
        if response is None:
            self.raise_uncaught_exception(exc)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
        response.exception = True
        return response
    def raise_uncaught_exception(self, exc):
        if settings.DEBUG:
Local vars
D:\Files\flowback-backend\venv\Lib\site-packages\rest_framework\views.py, line 480, in raise_uncaught_exception
    def raise_uncaught_exception(self, exc):
        if settings.DEBUG:
            request = self.request
            renderer_format = getattr(request.accepted_renderer, 'format')
            use_plaintext_traceback = renderer_format not in ('html', 'api', 'admin')
            request.force_plaintext_errors(use_plaintext_traceback)
        raise exc
             ^^^^^^^^^ …
    # Note: Views are made CSRF exempt from within `as_view` as to prevent
    # accidental removal of this exemption in cases where `dispatch` needs to
    # be overridden.
    def dispatch(self, request, *args, **kwargs):
        """
Local vars
D:\Files\flowback-backend\venv\Lib\site-packages\rest_framework\views.py, line 506, in dispatch
            # Get the appropriate handler method
            if request.method.lower() in self.http_method_names:
                handler = getattr(self, request.method.lower(),
                                  self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed
            response = handler(request, *args, **kwargs)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
        except Exception as exc:
            response = self.handle_exception(exc)
        self.response = self.finalize_response(request, response, *args, **kwargs)
        return self.response
Local vars
D:\Files\flowback-backend\flowback\user\views\user.py, line 132, in post
        website = serializers.CharField(required=False)
        dark_theme = serializers.BooleanField(required=False)
        contact_email = serializers.CharField(required=False)
        contact_phone = PhoneNumberField(required=False)
    def post(self, request):
        serializer = self.InputSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
        user_update(user=request.user, data=serializer.validated_data)
        return Response(status=status.HTTP_200_OK)
class UserDeleteAPI(APIView):
Local vars
D:\Files\flowback-backend\venv\Lib\site-packages\rest_framework\serializers.py, line 227, in is_valid
        assert hasattr(self, 'initial_data'), (
            'Cannot call `.is_valid()` as no `data=` keyword argument was '
            'passed when instantiating the serializer instance.'
        )
        if not hasattr(self, '_validated_data'):
            try:
                self._validated_data = self.run_validation(self.initial_data)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
            except ValidationError as exc:
                self._validated_data = {}
                self._errors = exc.detail
            else:
                self._errors = {}
Local vars
D:\Files\flowback-backend\venv\Lib\site-packages\rest_framework\serializers.py, line 426, in run_validation
        performed by validators and the `.validate()` method should
        be coerced into an error dictionary with a 'non_fields_error' key.
        """
        (is_empty_value, data) = self.validate_empty_values(data)
        if is_empty_value:
            return data
        value = self.to_internal_value(data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
        try:
            self.run_validators(value)
            value = self.validate(value)
            assert value is not None, '.validate() should return the validated data'
        except (ValidationError, DjangoValidationError) as exc:
            raise ValidationError(detail=as_serializer_error(exc))
Local vars
D:\Files\flowback-backend\venv\Lib\site-packages\rest_framework\serializers.py, line 479, in to_internal_value
                api_settings.NON_FIELD_ERRORS_KEY: [message]
            }, code='invalid')
        ret = OrderedDict()
        errors = OrderedDict()
        fields = self._writable_fields
        for field in fields:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
            validate_method = getattr(self, 'validate_' + field.field_name, None)
            primitive_value = field.get_value(data)
            try:
                validated_value = field.run_validation(primitive_value)
                if validate_method is not None:
                    validated_value = validate_method(validated_value)
Local vars
D:\Files\flowback-backend\venv\Lib\site-packages\rest_framework\serializers.py, line 362, in _writable_fields
        fields = BindingDict(self)
        for key, value in self.get_fields().items():
            fields[key] = value
        return fields
    @property
    def _writable_fields(self):
        for field in self.fields.values():
                          ^^^^^^^^^^^ …
            if not field.read_only:
                yield field
    @property
    def _readable_fields(self):
        for field in self.fields.values():
Local vars
D:\Files\flowback-backend\venv\Lib\site-packages\django\utils\functional.py, line 57, in __get__
        """
        Call the function and put the return value in instance.__dict__ so that
        subsequent attribute access on the instance returns the cached value
        instead of calling cached_property.__get__().
        """
        if instance is None:
            return self
        res = instance.__dict__[self.name] = self.func(instance)
                                                 ^^^^^^^^^^^^^^^^^^^ …
        return res
class classproperty:
    """
    Decorator that converts a method with a single cls argument into a property
Local vars
D:\Files\flowback-backend\venv\Lib\site-packages\rest_framework\serializers.py, line 356, in fields
        """
        A dictionary of {field_name: field_instance}.
        """
        # `fields` is evaluated lazily. We do this to ensure that we don't
        # have issues importing modules that use ModelSerializers as fields,
        # even if Django's app-loading stage has not yet run.
        fields = BindingDict(self)
        for key, value in self.get_fields().items():
                               ^^^^^^^^^^^^^^^^^ …
            fields[key] = value
        return fields
    @property
    def _writable_fields(self):
        for field in self.fields.values():
Local vars
D:\Files\flowback-backend\venv\Lib\site-packages\rest_framework\serializers.py, line 1027, in get_fields
        """
        Return the dict of field names -> field instances that should be
        used for `self.fields` when instantiating the serializer.
        """
        if self.url_field_name is None:
            self.url_field_name = api_settings.URL_FIELD_NAME
        assert hasattr(self, 'Meta'), (
              ^ …
            'Class {serializer_class} missing "Meta" attribute'.format(
                serializer_class=self.__class__.__name__
            )
        )
        assert hasattr(self.Meta, 'model'), (
            'Class {serializer_class} missing "Meta.model" attribute'.format(
Local vars

**Comment by Gofven** [comment]
Try and see if it works c:
