### ISSUE TITLE
"Poll is not in vote or dynamic, currently in delegate_vote"

### ISSUE THREAD

**Issue by Kattenelvis** [Gofven/flowback-backend#18]
Despite being delegate in the group, I get this error.

![image](https://github.com/Gofven/flowback/assets/53380638/e8a9920d-a3f0-44cf-a38f-ba3151724ba3)

**Comment by Gofven** [comment]
Are you using the vote API or the delegate vote API, delegate votes can only be sent trough Delegate Vote API

**Comment by Kattenelvis** [comment]
NVM this is how it's supposed to be, as Loke said
