### ISSUE TITLE
Expanded Permissions

### ISSUE THREAD

**Issue by Kattenelvis** [Gofven/flowback-backend#55]
New feature request for permissions:

1. One user should be able to have multiple permissions
2. New permissions: 
   a. Prediction statement create
   b. Prediction statement delete
   c. Prediction statement edit
   d. Prediction bet create
   e. Prediction bet delete
   f. Prediction bet edit

**Comment by Gofven** [comment]
Done and dusted!
Although multiple permissions isn't prioritized (for now)
