### ISSUE TITLE
Store blockchain id's on polls, proposals and prediction statements

### ISSUE THREAD

**Issue by Kattenelvis** [Gofven/flowback-backend#63]
The smart contracts return some ID value for polls, proposals and prediction statements that are not equal to their respective ID's. One possible solution is to store blockchain_id as a separate optional value that's passed in when creating those objects.

**Comment by Gofven** [comment]
Although i do get what you mean, wouldn't it be unsafe to rely on the users input to store the ID values from the end user?

**Comment by Kattenelvis** [comment]
> Although i do get what you mean, wouldn't it be unsafe to rely on the users input to store the ID values from the end user?

The frontend design will take the ID generated in metamask and input it automatically, I will not ask the user to input it. If someone where to put in a false ID using something like postman on create poll, then no one would be able to create any proposal or prediction blockchain pushes with it, which is just the same as if the poll had never been pushed in the first place. 

I'm not sure how else to do it

**Comment by Gofven** [comment]
Added all the nessesary features for it c:!
Although we might need to find a different way of solving this in the future!
