### ISSUE TITLE
Permissions for pollcreate doesn't work

### ISSUE THREAD

**Issue by Kattenelvis** [Gofven/flowback-backend#75]
I assigned permissions, but still got permission denied

**Comment by Kattenelvis** [comment]
Wait I got it to work somehow? We might wanna check more into this

**Comment by Gofven** [comment]
I don't see any easy to spot issues with this, perhaps you had allow_fast_forward set to True and aren't the group admin?

**Comment by Kattenelvis** [comment]
Yes that was exactly it
