### ISSUE TITLE
Area vote broken

### ISSUE THREAD

**Issue by Kattenelvis** [Gofven/flowback-backend#79]
Voting works, and gives 200, but the poll in poll list has the wrong tag id

**Comment by Gofven** [comment]
There's already tests that has been made for this, i'm uncertain how this error occurs, is there any more info you could give me?

**Comment by Kattenelvis** [comment]
Here's the API Process:

Sending at:	/group/poll/12/area/update
Request:  {tag:	14
vote:	true}


Sending at:	/group/poll/12/fast_forward
Request: {phase:	"proposal"}


Sending at: 	/group/11/poll/list?id=12
Response (Not request since this is a GET request): {
...
tag_id = 11
...
}

**Comment by Kattenelvis** [comment]
With status 200 on all of them, no error message.
