### ISSUE TITLE
Add interval_mean_absolute_error to Group Tags

### ISSUE THREAD

**Issue by Gofven** [Gofven/flowback-backend#81]
Create new variable "interval_mean_absolute_error" for GroupTags, display it for everyone

Assign the variable with following:
  For every combined_bet & outcome in a given tag:
    abs(sum(combined_bet) – sum(outcome))/N
    - N is the number of predictions that had at least one bet

**Comment by Gofven** [comment]
See if it works now c:

**Comment by Kattenelvis** [comment]
It works but you must close this issue
