### ISSUE TITLE
Area vote data

### ISSUE THREAD

**Issue by Kattenelvis** [Gofven/flowback-backend#84]
Either as a separate get request, or as a part of the poll list API.

**Comment by Gofven** [comment]
Test and see if it works now c:

**Comment by Kattenelvis** [comment]
Would be nice to have data on what area the user has voted on during area vote phase

**Comment by Kattenelvis** [comment]
I see it's in area vote list, but why is there no id field, only name?

**Comment by Kattenelvis** [comment]
It is also broken, it only works the first time one votes for an area, not the second time

**Comment by Gofven** [comment]
I need more information on this, what do you mean?
